[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "node server.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

# Aumentar timeouts pois o processamento de v√≠deo trava o event loop por milissegundos
healthcheckPath = "/health"
healthcheckTimeout = 300
healthcheckInterval = 30
serviceName = "bizerra-motor-v13"

[env]
NODE_ENV = "production"
PORT = "8080"